### ISSUE TITLE
mqtt-sn gate can not connect mqtt server？

### ISSUE THREAD

**Issue by freechw** [brianrho/mqttsn#1]
I use  esp8266 HC12 gateway,  but the gateway can not connect mqtt server normal,  alway reconnect,  and the  mqtt server log is:
```
1609397657: New client connected from 192.168.1.211 as ESP8266Client-5de0 (p2, c1, k60, u'mqttuser').
1609397748: Client ESP8266Client-5de0 has exceeded timeout, disconnecting.
1609397748: New connection from 192.168.1.211 on port 1883.
1609397748: New client connected from 192.168.1.211 as ESP8266Client-159a (p2, c1, k60, u'mqttuser').
1609397839: Client ESP8266Client-159a has exceeded timeout, disconnecting.
```

I modify the pubsubclient newest version v2.8,  but  the error is same.

Then I test the origin pubsubclient examples,  everything is run OK. 

Can you fix it.  thanks.

**Comment by freechw** [comment]
and can you  update PubsubClient to V2.8?

**Comment by freechw** [comment]
I knows where is the problem， because esp8266_hc12_gateway example  lost    mqttc.loop();   
I add it, and now run OK. but the new error is:

`[+]Got SUBSCRIBE.
[+]Topic name: led, ID: 1
[+]SUBACK sent.
[+]MQTT SUBSCRIBE to esp8266mqttsn/led.
[+]
[+]Got PUBLISH.
[+]MQTT PUBLISH to esp8266mqttsn/led

[+]Got MQTT PUBLISH to esp8266mqttsn/led.
[+]Dispatching msgs.
Fatal exception 28(LoadProhibitedCause):epc1=0x40201be6, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000--------------- CUT HERE FOR EXCEPTION DECODER ---------------
Exception (28):
epc1=0x40201be6 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffda0 end: 3fffffc0 offset: 0190
3fffff30:  3fffdad0 3fff0631 3ffee72c 40201b71  
3fffff40:  00010000 00000000 3fff0600 3fff0638  
3fffff50:  3fffda01 3ffe080c 3ffee9fe 40201d81  
3fffff60:  3ffefdfc 3ffefce8 3ffeea00 00000001  
3fffff70:  00000000 00000000 3fff07f4 3fff0870  
3fffff80:  00000000 00000000 00000001 3fff0870  
3fffff90:  3fffdad0 00000000 3fff0830 40201297  
3fffffa0:  feefeffe 00000000 3fff0830 402065a4  
3fffffb0:  feefeffe feefeffe 3ffe8508 40101851  
<<<stack<<<
--------------- CUT HERE FOR EXCEPTION DECODER ---------------H≈?1?)?
SDK:2.2.2-dev(38a443e)/Core:2.7.3-3-g2843a5ac=20703003/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-30-g92add50/BearSSL:5c771be
`
I will try to resolve it. 
Thanks a lot, this is a awesome project.

**Comment by freechw** [comment]
Now I found a bug in  mqttgateway.cpp  loop  function,
 `   if (clnt.is_subbed(tid))`
maybe is:
`   if (!clnt.is_subbed(tid))`

when I fix it, now run OK.

**Comment by brianrho** [comment]
Sorry, I have no idea how I totally missed this issue all this time. Thanks for letting me know, will look into and fix that.

**Comment by brianrho** [comment]
Done. You can reopen the issue if you still get the exception.

**Comment by brianrho** [comment]
For your question on upgrading the pubsubclient version, I really don't want to have to maintain my pubsubclient changes, especially as the upstream pubsubclient diverges (however slowly). Instead, I'll provide a different MQTT-interface example using this [library](https://github.com/256dpi/arduino-mqtt), that already contains the features I need, and is a richer MQTT client anyways.
